#!/bin/bash
# tested to work on the clean ubuntu instalation 

# uncomment out next 4 lines if you need git and clone 
#apt update
#apt install -y git
#git clone https://github.com/yesanton/Process-Drift-Visualization-With-Declare.git
#cd Process-Drift-Visualization-With-Declare/


# install python and required libs
apt-get install software-properties-common
add-apt-repository ppa:deadsnakes/ppa
apt-get update
apt-get install python3.8

apt install python3-pip
pip3 install sklearn
pip3 install ruptures
pip3 install matplotlib
pip3 install seaborn
pip3 install pm4py

#install java version 10
apt install wget
wget https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz
tar -xvf openjdk-10.0.2_linux-x64_bin.tar.gz
mkdir -p /usr/lib/jdk
mv jdk-10.0.2 /usr/lib/jdk
update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jdk/jdk-10.0.2/bin/java" 1 
update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jdk/jdk-10.0.2/bin/javac" 1
update-alternatives --config java
update-alternatives --config javac


export PYTHONPATH="$PWD"
python3 src/scenario_1.py -logName italian_help_desk -subL 100 -sliBy 50 
